name: Nodejs checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing packags
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    - name: Install dependencies
      run: npm install
    - run: npm run eslint
    - run: npm run run
      env:
        review: true
